const FETCH_MEMBERS = 'FETCH_MEMBERS';
const ADD_MEMBER = 'ADD_MEMBER';
const EDIT_MEMBER = 'EDIT_MEMBER';
const DELETE_USER = 'DELETE_USER';
const FETCH_TASKS = 'FETCH_TASKS';
const FETCH_USER_TASKS = 'FETCH_USER_TASKS';
const SET_USER_MARK = 'SET_USER_MARK';

export { FETCH_MEMBERS, ADD_MEMBER, EDIT_MEMBER, DELETE_USER, FETCH_TASKS, FETCH_USER_TASKS, SET_USER_MARK };
