const FETCH_MEMBERS = 'FETCH_MEMBERS';
const ADD_MEMBER = 'ADD_MEMBER';
const EDIT_MEMBER = 'EDIT_MEMBER';
const DELETE_USER = 'DELETE_USER';
const FETCH_TASKS = 'FETCH_TASKS';
const FETCH_USER_TASKS = 'FETCH_USER_TASKS';
const SET_USER_MARK = 'SET_USER_MARK';
const ADD_TASK = 'ADD_TASK';
const DELETE_TASK = 'DELETE_TASK';
const EDIT_TASK = 'EDIT_TASK';
const THROW_ALERT = 'THROW_ALERT';
const FETCH_DATA_START = 'FETCH_DATA_START';
const SET_FORM_DATA = 'SET_FORM_DATA';
const SET_ASSIGNED_MEMBERS = 'SET_ASSIGNED_MEMBERS';
const GET_USER_PROGRESS = 'GET_USER_PROGRESS';
const DELETE_USER_PROGRESS = 'DELETE_USER_PROGRESS';
const EDIT_USER_PROGRESS = 'EDIT_USER_PROGRESS';
const ADD_USER_PROGRESS = 'ADD_USER_PROGRESS';
const AUTH_LOG_IN = 'AUTH_LOG_IN';
const CHANGE_AUTH_STATUS = 'CHANGE_AUTH_STATUS';
const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
const AUTH_REGISTER = 'AUTH_REGISTER';
const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';

export {
  FETCH_MEMBERS,
  ADD_MEMBER,
  EDIT_MEMBER,
  DELETE_USER,
  FETCH_TASKS,
  FETCH_USER_TASKS,
  SET_USER_MARK,
  ADD_TASK,
  DELETE_TASK,
  EDIT_TASK,
  THROW_ALERT,
  FETCH_DATA_START,
  SET_FORM_DATA,
  SET_ASSIGNED_MEMBERS,
  GET_USER_PROGRESS,
  DELETE_USER_PROGRESS,
  EDIT_USER_PROGRESS,
  ADD_USER_PROGRESS,
  AUTH_LOG_IN,
  CHANGE_AUTH_STATUS,
  AUTH_LOG_OUT,
  AUTH_REGISTER,
  TOGGLE_DARK_MODE,
};
