import {
  getUsers,
  addUser,
  editUser,
  deleteUser,
  getTasks,
  getUserTasks,
  setMark,
  addTask,
  deleteTask,
  editTask,
  setFormData,
  setAssignedMembers,
  getUserProgress,
  deleteUserProgress,
  editUserProgress,
  addUserProgress,
  switchDarkMode,
  reorderTable,
} from './dataActions';
import { logIn, changeStatus, logOut, registerUser, startAuth, endAuth, changePassword } from './authActions';

export {
  getUsers,
  addUser,
  editUser,
  deleteUser,
  getTasks,
  getUserTasks,
  setMark,
  addTask,
  deleteTask,
  editTask,
  setFormData,
  setAssignedMembers,
  getUserProgress,
  deleteUserProgress,
  editUserProgress,
  addUserProgress,
  logIn,
  changeStatus,
  logOut,
  registerUser,
  switchDarkMode,
  startAuth,
  endAuth,
  changePassword,
  reorderTable,
};
